### ISSUE TITLE
What exactly does this do?

### ISSUE THREAD

**Issue by AdityaAnand1** [JimmyLaurent/cloudflare-scraper#3]
Can you please add some more details to the readme.

>Puppeteer (chromium headless) is used to retrieve cloudflare cookies then request module is used to perform requests making this solution reliable but also pretty fast.

What are some use-cases? Is this a workaround for cloudflare detection?

**Comment by JimmyLaurent** [comment]
This is in early stage and actually more like a POC for now. I prefer to focus on code rather than documenting.
That being said, the goal of this package is to help you scrape websites protected by cloudfare's IUAM (I'm Under Attack Mode) page.
If you don't know this protection: it's a series of javascript challenges to prove that you're not a bot.
Here is a picture:
![](https://images.ctfassets.net/slt3lc6tev37/55EYMR81XJCIG5uxLjQQOx/252a98adf90fa0ff2f70437cc5c0a3af/under-attack-mode_enabled.gif)

**Comment by AdityaAnand1** [comment]
Awesome! Looking forward to the future of this project! Would love to integrate it into my projects once it's ready 😁
